model:
  arch: annexe
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  prompt_template: '[INST] {} [/INST] '
  llama_model: "/home/suyuejiao/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf/snapshots/f5db02db724555f92da89c216ac04704f23d4590/"
  ckpt: "/mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/MiniGPT-4/minigptv2_ckpt/checkpoint_stage2.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  egoirgbench:
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
        mean: [0.55,0.55,0.53]
        std: [0.22,0.23,0.25]
      val:
        name: "blip2_image_eval"
        image_size: 448
        mean: [0.55,0.55,0.53]
        std: [0.22,0.23,0.25]
      test:
        name: "blip2_image_eval"
        image_size: 448
        mean: [0.55,0.55,0.53]
        std: [0.22,0.23,0.25]
    text_processor:
      train:
        name: "blip_caption"
      val:
        name: "blip_caption"
      test:
        name: "blip_caption"
    sample_ratio: 10  

    
run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 320
  num_workers: 6
  warmup_steps: 1000
  iters_per_epoch: 2544

  seed: 42
  output_dir: "/mnt/nvme1/suyuejiao/Final_rgbd_dataset/MiniGPT-4/ckpt_save_path/"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ['test']

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigptv2_finetune
