model:
  arch: annexe
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "/home/suyuejiao/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf/snapshots/f5db02db724555f92da89c216ac04704f23d4590/"
  ckpt: "/mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/MiniGPT-4/ckpt_save_path/first_setting/20241118162/checkpoint_42.pth"
  lora_r: 64
  lora_alpha: 16


datasets:
  cc_sbu_align:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  hm:
    eval_file_path: ""
    img_path: /mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/RGB/
    max_new_tokens: 20
    batch_size: 10

run:
  task: image_text_pretrain
  name: minigptv2_evaluation
  save_path: /mnt/nvme1/suyuejiao/Final_rgbd_dataset/MiniGPT-4/ckpt_save_path/20241022173/result/

  

  

