model:
  arch: annexe
  model_type: pretrain
  max_txt_len: 500
  end_sym: "</s>"
  low_resource: False
  prompt_template: '[INST] {} [/INST]'
  llama_model: "path/to/llama/model"
  ckpt: "path/to/your/checkpoint"
  lora_r: 64
  lora_alpha: 16


datasets:
  egoirgbench:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  egoirgbench:
    eval_file_path: ""
    img_path: path/to/dataset/RGB/folder
    max_new_tokens: 20
    batch_size: 10

run:
  task: image_text_pretrain
  name: annexe_eval
  save_path: path/to/your/saved/results

  

  


